"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Product_1 = require("./Product");
var ProductService_1 = require("./ProductService");
var _productService = new ProductService_1.ProductService();
var result;
result = _productService.getProducts();
console.log(result);
result = _productService.getById(2);
var p = new Product_1.Product();
p.name = "IPhone 5s";
p.price = 1200;
p.category = "Phone";
_productService.saveProduct(p);
console.log(result);
